# Jekyll Resume Theme

# Site settings
title: Cruze Resume
email: soragu@domain.com
name: 古宇昇
job: web开发工程师
location: 中国，广东，广州
github_username: soragu
email_address: soragu@email.com

# Build settings
encoding: utf-8
markdown: kramdown

